ClassStrategyCO = {};
ClassStrategyNC = {};

function InitializeStrategy()
	ClassStrategyCO = {
		[1] = {"grind","Self-Activity","The bot will search for targets within its vision and attack when it has no target in combat."},
		[2] = {"attack weak","Free Attack","The bot will freely choose targets to attack in combat."},
		[3] = {"attack force","Passive Attack","The bot will not choose targets in combat, you must manually specify the target to attack."},
		[4] = {"tank","Single Target Tank","The bot will only tank one target at a time, pulling the next one after killing the current one."},
		[5] = {"tank aoe","Multiple Target Tank","The bot will tank all targets in combat."},
		[6] = {"tank assist","Tank Assist","The bot will assist the tank role in the team by attacking the current target."},
		[7] = {"dps","Single Target DPS","The bot will only focus on one target for DPS, moving to the next one after killing the current one."},
		[8] = {"dps aoe","AOE DPS","The bot will use AOE skills when there are many targets in combat."},
		[9] = {"dps assist","DPS Assist","The bot will assist in DPSing the targets in the team."},
		[10] = {"dps debuff","Damage Buff","The bot will apply a damage-over-time buff to the target in combat."},
		[11] = {"heal","Heal Teammates","The bot will heal injured teammates in combat, stopping DPS."},
		[12] = {"aoe","AOE Attack","The bot will use AOE damage skills in combat."},
		[13] = {"flee","Keep Distance","The bot will try to run away when its current target gets too close in combat."},
		[14] = {"fire","Fire Spells","The bot will use fire spells to attack the target in combat. (For mage bots)"},
		[15] = {"fire aoe","Fire AOE","The bot will use fire AOE spells when there are many targets in combat. (For mage bots)"},
		[16] = {"frost","Frost Spells","The bot will use frost spells to attack the target in combat. (For mage bots)"},
		[17] = {"frost aoe","Frost AOE","The bot will use frost AOE spells when there are many targets in combat. (For mage bots)"},
		[18] = {"arcane","Arcane Spells","The bot will use arcane spells to attack the target in combat. (For mage bots)"},
		[19] = {"threat","Threat Control","The bot will output conservatively in combat to avoid over-aggro."},
		[20] = {"conserve mana","Mana Control","The bot will conserve its mana in combat, reducing its output."},
		[21] = {"shadow","Shadow Spells","The bot will use shadow spells to attack the target in combat. (For warlock and priest bots)"},
		[22] = {"shadow aoe","Shadow AOE","The bot will use shadow AOE spells when there are many targets in combat. (For warlock and priest bots)"},
		[23] = {"shadow debuff","Shadow Damage Buff","The bot will apply a shadow damage-over-time buff to the target in combat. (For warlock and priest bots)"},
		[24] = {"melee","Melee Combat","The bot will always stay close to the target for melee attacks in combat. (For shaman bots)"},
		[25] = {"melee aoe","Melee AOE","The bot will stay close to the target for AOE melee attacks in combat. (For shaman bots)"},
		[26] = {"rshadow","Shadow Resistance Aura","The bot will activate a shadow resistance aura in combat. (For paladin bots)"},
		[27] = {"rfrost","Frost Resistance Aura","The bot will activate a frost resistance aura in combat. (For paladin bots)"},
		[28] = {"rfire","Fire Resistance Aura","The bot will activate a fire resistance aura in combat. (For paladin bots)"},
		[29] = {"barmor","Armor Defense Aura","The bot will activate an armor defense aura in combat. (For paladin bots)"},
		[30] = {"bspeed","Mount Speed Aura","The bot will activate a mount speed aura in combat. (For paladin bots)"},
		[31] = {"rnature","Nature Resistance Aura","The bot will activate a nature resistance aura in combat. (For hunter bots)"},
		[32] = {"bhealth","Health Buff","The bot will apply a health-increasing buff to itself and teammates in combat."},
		[33] = {"bmana","Support Buff","The bot will apply support buffs to itself and teammates in combat."},
		[34] = {"bdps","Offensive Buff","The bot will apply offensive buffs to itself and teammates in combat."},
		[35] = {"bear","Bear Form","The bot will transform into a bear for DPS in combat. (For druid bots)"},
		[36] = {"cat","Cat Form","The bot will transform into a cat for DPS in combat. (For druid bots)"},
		[37] = {"cat aoe","Cat AOE","The bot will transform into a cat for AOE DPS in combat. (For druid bots)"},
		[38] = {"caster","Ranged Spell DPS","The bot will use ranged spells for DPS in combat. (For druid and shaman bots)"},
		[39] = {"caster aoe","Ranged AOE Spells","The bot will use ranged AOE spells when there are many targets in combat. (For druid and shaman bots)"},
		[40] = {"caster debuff","Ranged Damage Buff","The bot will apply a ranged damage-over-time buff to the target in combat. (For druid and shaman bots)"},
		[41] = {"totems","Totems","The bot will place totems around itself in combat. (For shaman bots)"},
		[42] = {"loot","Loot","The bot will loot nearby corpses in combat."},
		[43] = {"naxx","Naxxramas","The bot's behavior will be tailored for the Naxxramas instance. (Only effective in Naxxramas)"},
	};

	ClassStrategyNC = {
		[1] = {"grind","Self-Activity","The bot will search for targets within its vision and attack when not in combat."},
		[2] = {"move random","Random Movement","The bot will move around randomly when bored and not in combat."},
		[3] = {"attack weak","Free Attack","The bot will freely choose targets to attack at the moment of entering combat."},
		[4] = {"attack force","Passive Attack","The bot will not attack at all when not in combat, you must manually specify the target to attack."},
		[5] = {"bhealth","Health Buff","The bot will apply a health-increasing buff to itself and teammates when not in combat."},
		[6] = {"bmana","Support Buff","The bot will apply support buffs to itself and teammates when not in combat."},
		[7] = {"bdps","Offensive Buff","The bot will apply offensive buffs to itself and teammates when not in combat."},
		[8] = {"emote","Emote","The bot will randomly perform emote actions when bored and not in combat."},
		[9] = {"food","Rest","The bot will drink water and eat bread after leaving combat as needed."},
		[10] = {"loot","Loot","The bot will loot nearby corpses after leaving combat."},
		[11] = {"stay","Stay","The bot will stand still when not in combat."},
		[12] = {"follow","Follow","The bot will follow the player when not in combat."},
		[13] = {"quest","Quest","The bot will accept and complete quests with the NPC the player is interacting with when not in combat."},
		[14] = {"naxx","Naxxramas","The bot's behavior will be tailored for the Naxxramas instance. (Only effective in Naxxramas)"},
	};
end

